//
//  NewTaskViewController.swift
//  ViperToDo
//
//  Created Vladyslav Vdovychenko on 19.08.2020.
//  Copyright © 2020 Vladyslav Vdovychenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewTaskViewController: BaseViewController, NewTaskViewProtocol {

    @IBOutlet weak var taskTextField: UITextField!
    var presenter: NewTaskPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    @IBAction func didTappedOnSendTaskButton(_ sender: Any) {
        self.uploadTask()
    }
    
    @IBAction func didTappedOnSendTaskBarButtonItem(_ sender: Any) {
        self.uploadTask()
    }
    
    func showError(_ error: Error?) {
        self.handleError(error)
    }
    
    func uploadTask() {
        let task = Task(text: taskTextField.text!, date: Date())
        presenter?.uploadTask(task)
    }

}
