//
//  NewTaskPresenter.swift
//  ViperToDo
//
//  Created Vladyslav Vdovychenko on 19.08.2020.
//  Copyright © 2020 Vladyslav Vdovychenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewTaskPresenter: BasePresenter, NewTaskPresenterProtocol {
    
    
    weak var view: NewTaskViewProtocol?
    
    var interactor: NewTaskInteractorInputProtocol?
    
    var wireframe: NewTaskWireframeProtocol?
    
    weak var newTaskDelegate: NewTaskDelegate?
    
    func goBackToParent() {
        guard let view = view else { return }
        wireframe?.goBackToParent(from: view)
    }
    
    func uploadTask(_ task: Task) {
        interactor?.uploadTask(task)
    }

}

extension NewTaskPresenter: NewTaskInteractorOutputProtocol {
    
    func didUploadTask() {
        newTaskDelegate?.didUploadTask()
        self.goBackToParent()
    }
    
    func onError(_ error: Error?) {
        view?.showError(error)
    }
    
}
