//
//  ListInteractor.swift
//  ViperToDo
//
//  Created Vladyslav Vdovychenko on 18.08.2020.
//  Copyright © 2020 Vladyslav Vdovychenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ListInteractor: BaseInteractor, ListInteractorInputProtocol {
    
    weak var presenter: ListInteractorOutputProtocol?
    var remoteDataManager: ListRemoteDataManagerInputProtocol?
    
    func retrieveTaskList() {
        remoteDataManager?.retrieveTaskList()
    }
}

extension ListInteractor: ListRemoteDataManagerOutputProtocol {
    
    func onTaskRetrieved(_ tasks: [Task]) {
        presenter?.didReceiveTasks(tasks)
    }
    
    func onError(_ error: Error?) {
        presenter?.onError(error)
    }
    
    
}
