//
//  NewTaskInteractor.swift
//  ViperToDo
//
//  Created Vladyslav Vdovychenko on 19.08.2020.
//  Copyright © 2020 Vladyslav Vdovychenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewTaskInteractor: BaseInteractor, NewTaskInteractorInputProtocol {

    weak var presenter: NewTaskInteractorOutputProtocol?
    var remoteDataManager: NewTaskRemoteDataManagerInputProtocol?
    
    func uploadTask(_ task: Task) {
        remoteDataManager?.uploadTask(task)
    }
}

extension NewTaskInteractor: NewTaskRemoteDataManagerOutputProtocol {
    
    func onTaskUploaded() {
        presenter?.didUploadTask()
    }
    
    func onError(_ error: Error?) {
        presenter?.onError(error)
    }
    
    
}
